/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'redirectUrl', 'token', 'usedAt', 'userId'] as const
  $columns = AuthTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare redirectUrl: string
  @column()
  declare token: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class CacheSchema extends BaseModel {
  static $columns = ['expiresAt', 'key', 'value'] as const
  $columns = CacheSchema.$columns
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare value: string | null
}

export class CompanySchema extends BaseModel {
  static $columns = ['createdAt', 'document', 'id', 'isActive', 'legalName', 'logoUrl', 'name', 'ownerUserId', 'phone', 'planId', 'slug', 'stateRegistration', 'updatedAt'] as const
  $columns = CompanySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare document: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare legalName: string | null
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare ownerUserId: number
  @column()
  declare phone: string | null
  @column()
  declare planId: number | null
  @column()
  declare slug: string
  @column()
  declare stateRegistration: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompanyAddressSchema extends BaseModel {
  static $columns = ['city', 'companyId', 'complement', 'country', 'createdAt', 'id', 'isPrimary', 'label', 'neighborhood', 'number', 'state', 'street', 'updatedAt', 'zipCode'] as const
  $columns = CompanyAddressSchema.$columns
  @column()
  declare city: string
  @column()
  declare companyId: number
  @column()
  declare complement: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPrimary: boolean | null
  @column()
  declare label: string | null
  @column()
  declare neighborhood: string | null
  @column()
  declare number: string | null
  @column()
  declare state: string
  @column()
  declare street: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zipCode: string
}

export class CompanyMemberSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'id', 'roleId', 'userId'] as const
  $columns = CompanyMemberSchema.$columns
  @column()
  declare companyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: number | null
  @column()
  declare userId: number
}

export class FeatureGroupSchema extends BaseModel {
  static $columns = ['createdAt', 'icon', 'id', 'isActive', 'moduleId', 'name', 'position', 'slug', 'updatedAt'] as const
  $columns = FeatureGroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare moduleId: number
  @column()
  declare name: string
  @column()
  declare position: number | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FeatureSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'featureGroupId', 'icon', 'id', 'isActive', 'isMenuItem', 'moduleId', 'name', 'position', 'route', 'slug', 'updatedAt'] as const
  $columns = FeatureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare featureGroupId: number | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare isMenuItem: boolean | null
  @column()
  declare moduleId: number | null
  @column()
  declare name: string
  @column()
  declare position: number | null
  @column()
  declare route: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LockSchema extends BaseModel {
  static $columns = ['expiration', 'key', 'owner'] as const
  $columns = LockSchema.$columns
  @column()
  declare expiration: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare owner: string
}

export class ModuleSchema extends BaseModel {
  static $columns = ['createdAt', 'icon', 'id', 'isActive', 'name', 'position', 'slug', 'updatedAt'] as const
  $columns = ModuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare position: number | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PlanModuleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'limits', 'moduleId', 'planId'] as const
  $columns = PlanModuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare limits: any | null
  @column()
  declare moduleId: number
  @column()
  declare planId: number
}

export class PlanSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'name', 'price', 'slug', 'updatedAt'] as const
  $columns = PlanSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare price: number | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'dedupAt', 'dedupId', 'dedupTtl', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare dedupAt: bigint | number | null
  @column()
  declare dedupId: string | null
  @column()
  declare dedupTtl: bigint | number | null
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RoleFeatureSchema extends BaseModel {
  static $columns = ['createdAt', 'featureId', 'id', 'roleId'] as const
  $columns = RoleFeatureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare featureId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'description', 'id', 'isDefault', 'name', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column()
  declare companyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TeamMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'teamId', 'userId'] as const
  $columns = TeamMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare teamId: number
  @column()
  declare userId: number
}

export class TeamSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'id', 'name', 'roleId', 'slug', 'updatedAt'] as const
  $columns = TeamSchema.$columns
  @column()
  declare companyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare roleId: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'coverUrl', 'createdAt', 'email', 'fullName', 'id', 'password', 'roleId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare coverUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare roleId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
